#!/usr/bin/python
# -*- coding: UTF-8 -*-

import sys
import os
import pickle
import random
import subprocess

#Configuração de pasta base
QUESTS_DIR = "quests"

def get_project_paths(class_name):

    """Retorna os caminhos dos arquivos isolados por pasta de turma."""

    base_dir = os.path.join(".", class_name)
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)

    return {
        'DIR': base_dir,
        'PROJECT': os.path.join(base_dir, "project.comp"), #fica dentro da pasta
        'PROVAS': os.path.join(base_dir, "provas.tex"), #fica dentro --
        'REPORT': os.path.join(base_dir, "report.txt"), #same
        'REPORT_TEX': os.path.join(base_dir, "report_notas.tex"),
        'STUDENTS': os.path.join(base_dir, "students.txt")}   



#abre um arquivo, lê os bytes bin. e reconstrói o dic. como estava antes
def load_project(path): 
    if os.path.exists(path):
        with open(path, 'rb') as f:
            return pickle.load(f)
    return {}



#recebe o dic. do proj. e guarda num arquivo físico
def save_project(path, data): 
    with open(path, 'wb') as f:
        pickle.dump(data, f) 



#leitor inteligente de questões, abre os arquivos de texto das perguntas e traduz o formato de texto
def parse_question_file(filename): 
    """

    Lê a questão da pasta quests e aceita qualquer número de alternativas,
    após isso, 
    ele retorna o enunciado e uma lista de tuplas: (id_item, status, texto)

    """


    path = os.path.join(QUESTS_DIR, filename)
    if not os.path.exists(path):
        return None
    
    enunciado = ""
    alternativas = []

    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    for line in lines:
        line_str = line.strip()
        if line_str.startswith("%%") or not line_str:
            continue
        if line_str.startswith("\\quest"):
            enunciado = line_str.replace("\\quest", "").strip()
        elif line_str.startswith("\\item"):

            #Exemplo: \item{1,c} azul -> extrai o miolo interno {1,c}
            start_bracket = line_str.find("{")
            end_bracket = line_str.find("}")
            meta = line_str[start_bracket + 1: end_bracket].split(',')
            item_id = meta[0].strip()
            status = meta[1].strip()
            texto = line_str[end_bracket+1:].strip()
            alternativas.append((item_id, status, texto))

    return{"enunciado": enunciado, "alternativas": alternativas}



#função para as notas calculadas do relatório, diz o que está escrito nos arquivos de questões naquele momento
def get_correct_answers():

    """Lê dinamicamente a pasta de questões para saber o gabarito real atualizado."""

    gabarito_real = {}

    #Busca quest01.txt, quest02.txt dinamicamente na pasta quests

    if not os.path.exists(QUESTS_DIR):
        return gabarito_real
    
    for file in os.listdir(QUESTS_DIR):

        if file.startswith("quest") and file.endswith(".txt"):

            q_num = file.replace("quest", "").replace(".txt", "")
            q_data = parse_question_file(file)

            if q_data:
                for item_id, status, _ in q_data["alternativas"]:
                    if status == 'c':
                        gabarito_real[q_num] = item_id

    return gabarito_real



#Execução do código 
if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Uso correto: python3 shc_2_1.py <NOME_DA_TURMA> --<comando> [argumentos]")
        print("Exemplos:")
        print("  python shc_2_1.py turma_a --submit 01 abc")
        sys.exit(1)

    turma = sys.argv[1] #Captura o primeiro argumento do terminal (o nome da turma)
    cmd = sys.argv[2] # Gera o mapeamento isolado para essa turma

    paths = get_project_paths(turma)

    if cmd == "--create":
        cmd_create(paths)
    elif cmd == "--exams":
        cmd_exams(paths)
    elif cmd == "--submit":
        if len(sys.argv) < 5:
            printf("Erro: forneça o serial e as respostas. Ex: python3 shc_2_2.py turma_a --submit 01 abc")
        else:
            cmd_submit(paths, sys.argv[3], sys.argv[4])
    elif cmd == "--report":
            cmd_report(paths)
        else:
            print("[-] Comando desconhecido.")